version: '3'
services:
  web:
    build:
        context: ./
        dockerfile: docker/php72_apache.docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html
    links:
        - mysql
    environment:
        - "DB_PORT=3306"
        - "DB_HOST=mysql"
  mysql:
      image: mysql:5.7
      volumes:
          - ./docker/mysql:/var/lib/mysql
      environment:
          - "MYSQL_ROOT_PASSWORD=root"
          - "MYSQL_USER=root"
          - "MYSQL_PASSWORD=root"
      ports:
          - "3306:3306"
